version: '3.8'
services:
  movieteka:
    build: .
    restart: always
    image: movieteka
    ports:
      - '8080:8080'
    depends_on:
      - postgresql_db
    links:
      - postgresql_db:postgresql_db

  postgresql_db:
    image: postgres:15.1-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movieteka_db
    ports:
      - '9000:5432'

